# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=4)),
                ('firsttimestamp', models.DateTimeField()),
                ('lasttimestamp', models.DateTimeField()),
                ('firstpointlatitude', models.FloatField()),
                ('firstpointlongitude', models.FloatField()),
                ('lastpointlatitude', models.FloatField()),
                ('lastpointlongitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('continent', models.CharField(max_length=20)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
