# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='continent',
        ),
    ]
