# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0004_trips_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='velocity',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
