# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0005_trips_velocity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='npoints',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
