# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0008_trips_citytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripAccelerations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naccelerations', models.IntegerField(blank=True, default=None, null=True)),
                ('nbreaks', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trips',
            name='naccelerations',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='nbreaks',
        ),
        migrations.AddField(
            model_name='tripaccelerations',
            name='tripid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behaviour.Trips'),
        ),
    ]
