# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0009_auto_20170428_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('device_id', models.CharField(max_length=4)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.IntegerField()),
                ('tripid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='behaviour.Trips')),
            ],
        ),
    ]
