# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0010_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='speed',
            field=models.FloatField(),
        ),
    ]
