# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0013_remove_points_tripid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAttribs',
            fields=[
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='behaviour.Points')),
                ('timestamp', models.DateTimeField()),
                ('device_id', models.CharField(max_length=4)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='points',
            name='hasTrip',
            field=models.BooleanField(default=False),
        ),
    ]
