# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0014_auto_20170512_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripaccelerations',
            name='tripid',
        ),
        migrations.AddField(
            model_name='trips',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='hasTrip',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='trips',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trips',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TripAccelerations',
        ),
    ]
