# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0015_auto_20170514_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointsattribs',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='pointsattribs',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pointsattribs',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='pointsattribs',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='pointsattribs',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='pointsattribs',
            name='dayofweek',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pointsattribs',
            name='isweekend',
            field=models.BooleanField(default=False),
        ),
    ]
