# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0016_auto_20170515_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='dayofweek',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='isweekend',
            field=models.BooleanField(default=False),
        ),
    ]
