# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0017_auto_20170515_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='pnaccelerations',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='pnbreaks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
