# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0018_auto_20170519_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='firsttimerange',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trips',
            name='lasttimerange',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
