# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0019_auto_20170521_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='trips',
            name='stresslevel',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
