# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0020_trips_stresslevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressCity',
            fields=[
                ('city', models.IntegerField(primary_key=True, serialize=False)),
                ('high', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StressCountry',
            fields=[
                ('country', models.IntegerField(primary_key=True, serialize=False)),
                ('high', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StressState',
            fields=[
                ('state', models.IntegerField(primary_key=True, serialize=False)),
                ('high', models.IntegerField(default=0)),
                ('mid', models.IntegerField(default=0)),
                ('low', models.IntegerField(default=0)),
            ],
        ),
    ]
