# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0021_stresscity_stresscountry_stressstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StressCity',
        ),
        migrations.DeleteModel(
            name='StressCountry',
        ),
        migrations.DeleteModel(
            name='StressState',
        ),
    ]
