# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviour', '0023_stresscity_stresscountry_stressstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stresscity',
            name='city',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='stresscountry',
            name='country',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='stressstate',
            name='state',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
